### ISSUE TITLE
workflows not displayed any more

### ISSUE THREAD

**Issue by PerrineGilloteaux** [NEUBIAS/bise#204]
still working on test.biii.eu, but is not working with a former db export from april , neither from the one in 2021. Was however beginning of the year, so maybe javascript  or theme update related?  web/themes/custom/projet/js/bise-core-ontology-master/wf-html-vis/main.js

**Comment by PerrineGilloteaux** [comment]
Working again right now ? Could be related to Cache Clearing ? I was going to do so... Did someone did something???
![image](https://github.com/NEUBIAS/bise/assets/19286219/032b77ea-a58a-4af2-a707-588558845646)
http://biii.eu/microtubules-tool-3d

**Comment by miura** [comment]
Hi @PerrineGilloteaux , (cc @czhci ) it might be because of the PHP version but not sure. In the dev site, the workflow does not appear (test.biii.eu is currently running with PHP version 7.4, which should not and should be at least 8.0)

https://test.biii.eu/microtubules-tool-3d

and the error is:
![image](https://github.com/NEUBIAS/bise/assets/272781/14cb46da-2880-4c59-83bd-b0cf55b2540f)

As the production site and the test cannot have different PHP version (.ohvconfig file with different PHP versions in each subdomain does not work at the moment). This is the similar situation like the one reported here:

https://community.ovh.com/en/t/php-compatibility-issue-between-two-different-subdomains/14116

So I will test with more modern PHP version and make sure that it works with this microtubule page. Otherwise, I will not upgrade the production site from drupal 8.9 to 9.5.

**Comment by miura** [comment]
Hi @PerrineGilloteaux 

thanks, it's because of that. here is the explanation:

![image](https://github.com/NEUBIAS/bise/assets/272781/d07f40b4-93c5-407f-86e8-3fe8e2d8f5d6)

I will try to look for what I can do.

**Comment by miura** [comment]
The above commit fixed the test site for this issue. It will probably fix the main site in 8.9 as well, because it's an issue with javascript and security. Let's see...

**Comment by miura** [comment]
waiting for deployment in the production site

**Comment by miura** [comment]
Fixed. 
https://biii.eu/microtubules-tool-3d
