### ISSUE TITLE
Error on taxonomy menu with update to 8.6.7 drupal core

### ISSUE THREAD

**Issue by PerrineGilloteaux** [NeuBIAS/bise#48]
This issue comes from 2 bugs in the taxonomy_menu , only one has been fixed by patch so better to stick to taxonomy menu 3.3 (see composer json commit in fork from me and Chong), will be "pull requested soon"

**Comment by miura** [comment]
Hi @czhci @PerrineGilloteaux 

yes, please pull request that commits, specifically for composer.json!

**Comment by PerrineGilloteaux** [comment]
I did a pull request to dev

**Comment by miura** [comment]
Hi @PerrineGilloteaux , I found your commit 
PerrineGilloteaux@90b5a14bdca5ad61e7a49e753663a6830858ea77 , thanks, however, 

1. I think you did not pull request to NEUBIAS/bise, but this is OK because
2. this commit also has changes to .htaccess file which is not related. These two changes should be two different commits

As the change in composer.json is just a deletion of a char, I will do it separately (freeze drupal_taxonomy version to 3.3). If you see that, please `git pull upstream dev` soon and check if that becomes merged in your local repo automatically without any problem. 

just to draw attention, I quote @czhci

**Comment by miura** [comment]
done: ad771be7de0b8cae2bfc64bfa395bbcf537bbcb3
