### ISSUE TITLE
replace node number in URL to meaningful text, for training material, etc? (now only for software content type)

### ISSUE THREAD

**Issue by czhci** [NeuBIAS/bise#55]

**Comment by PerrineGilloteaux** [comment]
See commit 501426b3e41cb2d54cc20f669e5403b87f0e8ce5

**Comment by miura** [comment]
It looks like this is not done yet.

For example, taking colocalization training material from the list

   http://biii.eu/all-content?type=book&field_type_target_id=All

Then the URL shown is 

   http://biii.eu/node/1451

**Comment by PerrineGilloteaux** [comment]
http://biii.eu/3d-colocalisation [1] 

Actually (and it is the same with software entry or dataset entries) the
first time you enter it, the nice path plugin is not ran, it is ran only
second time you open it for edition. 

So the problem is: trying to understand why not run at the first
creation, but only at the first edition. 

Links:
------
[1] http://biii.eu/3d-colocalisation

**Comment by miura** [comment]
@PerrineGilloteaux I just now tried reindexing Pathauto (see below): It does then work in my local to generate aliases automatically. As this updating is not config-exportable, I will directly do it in the production site after pulling recent updates... so it's better be done from time to time. 

![image](https://user-images.githubusercontent.com/272781/54057267-b967f600-41f2-11e9-9e5b-ac0b79a9c9c4.png)
