### ISSUE TITLE
Personal tagger page CURATED tab does not show enough information

### ISSUE THREAD

**Issue by PerrineGilloteaux** [NeuBIAS/bise#92]
It shows only new entry cretaed by a tagger, but not the one modified from somebody else or any comment done. It is then underestimating the work of taggers. (example) http://biii.eu/user/1 when I did modify Acquiarium entry)

**Comment by miura** [comment]
It seems that revision is taken into account and listed in the "Curated" in the profile page of each. As an example, below is my "Curated" list, and as you see, a page created by you is listed there because I revised it. 

![image](https://user-images.githubusercontent.com/272781/67530943-0dabe180-f6c1-11e9-89f4-5b1434771c3d.png)

So the new feature you want is to have also pages that you commented on in the "Curated" list. I tired a bit but failed so far. So please create a new issue, that focuses on adding commented pages to the "Curated" list in the profile page of each.
